QandA/QandA/urls.py
"""
Definition of urls for QandA.
"""

from datetime import datetime
from django.conf.urls import patterns, url
from app.forms import BootstrapAuthenticationForm
import app
import app.views
import django.contrib.auth.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^question/create$', app.views.create_question, name = "create_question"),
    url(r'^question/(?P<pk>\d+)$', app.views.QuestionDetailView.as_view(template_name='app/questions/details.html'), name = "Question Detail"),

    url(r'^question/comment$', app.views.make_question_comment, name = "make_question_comment"),
    url(r'^question/answer$', app.views.answer_a_question, name = "answer_a_question"),
    url(r'^question/answer/comment$', app.views.make_answer_comment, name = "make_answer_comment"),
    url(r'^question/vote$', app.views.make_a_vote, name = "make_a_vote"),
        #url(r'^$', HomePageView.as_view(), name='home'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

QandA/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from app.models import *
from ckeditor.fields import RichTextField

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        body = RichTextField()
        fields = ["title", "body"] 

class CommentForm(forms.ModelForm):
    class Meta:
        model = QuestionComment
        question_id = forms.IntegerField()
        fields = ["text"]

QandA/app/templates/app/questions/comments-partial.html
{% load datetime_extras %}
{% load uuid_extras %}

<div class="row small">
    <div class="col-md-1"></div>
    <div class="col-md-11">
        {% for comment in comments %}
            <div class="row {% cycle 'bg-comment' 'bg-comment-row' %} bg-comment-hover small">
                <div class="col-md-9">
                    {{ comment.text }}
                </div>
                <div class="col-md-3 text-right small">
                    <a>{{comment.app_user.user.username|lower}}</a><span class="small"> - {{ comment.created_in|datetime:"%b %d '%y at %H:%M" }}</span>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% if answer == None %}
    {% include 'app/questions/create-question-comment-partial.html'%}
{% else %}
    {% include 'app/questions/create-answer-comment-partial.html'%}
{% endif %}

QandA/app/templates/app/questions/create-answer-comment-partial.html
{% load datetime_extras %}
{% load uuid_extras %}
<!-- Create a comment -->
{% uuid uuid_val %}
{% with uuid_val as uuid%}

<div class="row text-right">
    <div class="col-lg-12">
        <span id="txt-leave-comment" data-toggle data-toggle-for="frm-make-comment-{{ uuid }}"><a href="#">add a comment</a></span>
        <form action="{% url 'make_answer_comment' %}" method="post" class="form" id="frm-make-comment-{{ uuid }}" style="display: none;">
            <div class="form-group">
                {% csrf_token %}
                <input type="hidden" id="id_question_id" name="question_id" value="{{ question.id }}" />
                <input type="hidden" id="id_answer_id" name="answer_id" value="{{ answer.id }}" />
                <div class="form-group">
                    <input class="form-control" id="id_comment" maxlength="500" name="comment" placeholder="Comment" required="required" title="" type="text">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-star"></span> Submit
            </button>
        </form>
    </div>
</div>
{% endwith%}

QandA/app/templates/app/questions/create-question-comment-partial.html
{% load datetime_extras %}
{% load uuid_extras %}

<!-- Create a comment -->
{% uuid uuid_val %}
{% with uuid_val as uuid%}

<div class="row text-right">
    <div class="col-lg-12">
    <span id="txt-leave-comment" data-toggle data-toggle-for="frm-make-comment-{{ uuid }}"><a>add a comment</a></span>
        <form action="{% url 'make_question_comment' %}" method="post" class="form" id="frm-make-comment-{{ uuid }}" style="display: none;">
            <div class="form-group">
                {% csrf_token %}
                <input type="hidden" id="id_question_id" name="question_id" value="{{ question.id }}" />
                <div class="form-group">
                    <input class="form-control" id="id_comment" maxlength="500" name="comment" placeholder="Comment" required="required" title="" type="text">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-star"></span> Submit
            </button>
        </form>
    </div>
</div>
{% endwith%}

QandA/app/templates/app/questions/create.html
{% extends "app/layout.html" %}

{% load bootstrap3 %}
{% load wysiwyg %}


{% block content %}

{% wysiwyg_setup %}

<form action="" method="post" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}
    {% wysiwyg_editor "id_body" %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>

{% endblock %}

QandA/app/templates/app/questions/details.html
{% extends "app/layout.html" %}

{% load wysiwyg %}
{% load datetime_extras %}
{% load uuid_extras %}
{% load list_extras %}
{% block content %}

{% wysiwyg_setup %}

        <div class="row">

            <!-- Question Content Column -->
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-lg-1"></div>
                    <div class="col-md-11">
                         <!-- Title -->
                        <h1>{{ question.title }}</h1>

                        <hr>
                        <!-- Author Date/Time -->
                        {% if question.days_since_post < 7 %}
                            <span class="glyphicon glyphicon-time"></span> Asked {{ question.created_in|timesince }} ago by <a href="#">{{ question.creator.user.username|lower }}</a>
                        {% else %}
                            <span class="glyphicon glyphicon-time"></span> Asked on {{ question.created_in }} by <a href="#">{{ question.creator.user.username|lower }}</a>
                        {% endif%}

                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-1">
                        {% with data_vote='question' %}
                        {% include 'app/questions/vote-partial.html' %}    
                        {% endwith %}                   
                    </div>
                    <div class="col-md-11">
                        <!-- Question Body -->
                        {{ question.body|safe }}
                        
                        <hr>

                        <!-- Comments -->
                        {% with question.questioncomment_set.all as comments %}
                            {% include 'app/questions/comments-partial.html' %}
                        {% endwith %}                

                        <hr />
                    </div>
                </div>               

                <!-- Answers -->
                {% for answer in question.answer_set.all|sort_answer %}
                <div class="row">
                    <div class="col-xs-1">
                        {% with data_vote='answer' %}
                        {% include 'app/questions/vote-partial.html' %}    
                        {% endwith %}                   
                    </div>
                    <div class="col-lg-11">
                        <div class="row">
                            <div class="col-md-12">
                                {{ answer.body|safe }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-right">
                                Answered by <a>{{ answer.creator.user.username }}</a><span class="small"> at {{ answer.created_in|datetime:"%b %d '%y at %H:%M" }}</span>
                            </div>
                        </div>
                        <hr />

                        {% with answer.answercomment_set.all as comments %}
                            {% include 'app/questions/comments-partial.html' %}
                        {% endwith %}  
                    </div>
                </div>
                {% endfor%}

                <!-- New Answer Form-->
                <h5 id="txt-create-answer" data-toggle data-toggle-for="frm-create-answer"><a>New Answer</a></h5>
                <form action="{% url 'answer_a_question' %}" method="post" class="form" id="frm-create-answer" style="display:none;">
                    <div class="form-group">
                        {% csrf_token %}
                        <input type="hidden" id="id_question_id" name="question_id" value="{{ question.id }}" />
                        <div class="form-group">
                            <textarea class="form-control" cols="40" id="id_body" name="body" placeholder="Body" rows="10" title=""></textarea>
                        </div>
                    </div>
                    {% wysiwyg_editor "id_body" %}
                    <button type="submit" class="btn btn-primary">
                        <span class="glyphicon glyphicon-star"></span> Submit
                    </button>
                </form>
            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Question Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Related Questions</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled">
                                <li><a href="#">Question Name</a>
                                </li>
                                <li><a href="#">Question Name</a>
                                </li>
                                <li><a href="#">Question Name</a>
                                </li>
                                <li><a href="#">Question Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Recent Questions</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
{% endblock %}


{% block scripts %}
<script>
    $(document).ready(function () {
        $('[data-toggle]').click(function () {
            return toggleWriteCommentAnswer($(this));
        });

        $('[data-vote]').click(function () {
            return vote($(this));
        });
    });

    function toggleWriteCommentAnswer(element) {
        var elementnamefor = '#' + element.data('toggle-for');
        if (elementnamefor === '#undefined')
            return;
        var elementfor = $(elementnamefor);
        elementfor.slideToggle();
        textbox = elementfor.find('input');
        textbox.focus();
        return false;
    }

    function vote(element) {
        var voted_class_l = 'glyphicon-just-voted-l';
        var voted_class_d = 'glyphicon-just-voted-d';

        var span = element.children()[0];
        if ($(span).hasClass(voted_class_l) || $(span).hasClass(voted_class_d))
            return false;

        var votefor = element.data('vote');
        var question_id = element.data('question_id');
        var answer_id = element.data('answer_id');
        var vote_type = element.data('vote_type');
        var url = element.attr('href');



        $.post(url, {
            'question_id': question_id,
            'votefor': votefor,
            'answer_id': answer_id,
            'vote_type': vote_type
        }, function (data) {
            if (data == true) {
                if (vote_type == 'like')
                    $(span).addClass(voted_class_l);
                else
                    $(span).addClass(voted_class_d);
            }
            else
                console.log('vote result: ' + data);
        });

        return false;
    }

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
            }
        }
    });

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
{% endblock %}

QandA/app/templates/app/questions/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/blog-post.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

      
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

QandA/app/templates/app/questions/vote-partial.html
<div class="row text-center">
    <a href="{% url 'make_a_vote' %}" onclick="return false;" data-vote="{{ data_vote }}" data-question_id="{{ question.id }}" data-answer_id="{{ answer.id }}" data-vote_type="like"><span class="glyphicon glyphicon-thumbs-up glyphicon-vote"></span></a>
</div>
<hr />
<div class="row text-center">
    <a href="{% url 'make_a_vote' %}" onclick="return false;" data-vote="{{ data_vote }}" data-question_id="{{ question.id }}" data-answer_id="{{ answer.id }}" data-vote_type="deslike"><span class="glyphicon glyphicon-thumbs-down glyphicon-vote"></span></a>
</div>